server:
  port: 8080
spring:
  elasticsearch:
    uris: http://127.0.0.1:9200
  datasource:
    url: jdbc:mysql://localhost:3306/tc_db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: +yle9g_pps%J
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  mapper-locations: classpath:mappers/*.xml
